[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "7ab73f0f29f97ebd45c615af410d04934c065ddc"
libgfortran_version = "5.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "e3f24d3a87777e14ee779a236db763e6fe1da6adb232eea96a6758d31a0789c2"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "162186bd1d54d066144373321a797d5cb04f3ace"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[PROPACK.download]]
    sha256 = "7247c44e113833cd4fc11b278785cc0ec87cedaff3fd58534e874fd1e25b33c7"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "487925e686d8398d86b8589f7e85e793184323ff"
libgfortran_version = "3.0.0"
os = "macos"

    [[PROPACK.download]]
    sha256 = "9bf0d3793fae9081a3a2c3a2b94efaea87bc708350702564919c28651b4ddcd1"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "77e18f9f4e6dab81c2a7ed10a81c57e2288d0031"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "a2ff5e8d518f9101dff55b323347f447a92f54858e367e47a30b7f283b3a6b06"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "9389c5c1f6e11d3febd94c0f3fcc8a04e7602852"
libgfortran_version = "4.0.0"
os = "macos"

    [[PROPACK.download]]
    sha256 = "9889a303b3ddb5a165e664ab46205d2e1e56d71ad612a5309797ae0b7d28c945"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "108aba40c0c4a425bc36c7f44f9ea662a0f5b8ad"
libgfortran_version = "5.0.0"
os = "macos"

    [[PROPACK.download]]
    sha256 = "759e491dc7e011e3792ce09cab88026475de7e2f2a12fd4ca90d4dcdfa8eed72"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[PROPACK]]
arch = "armv7l"
git-tree-sha1 = "6bc17ad363161c2ff9f05cba5d44aec5dc7e174f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "d685efcfc46b41b429f582abf9985b390a564d7df0133dc8eece38d628b99864"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "8c8ac38c227a12e8c16e2e3f47011d42313c291e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "9c7da7ce79368bdfb86642bfc22a0f596a7be4a0fc0478e0b3bc23786094078d"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "1e1f30fa08190abfc85f69b1a083202249f1f79f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "0dee243fa5fdf2cf14f172bf55b9d11c6bb8878fdd6dad942dff3a2c6703ae52"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.i686-linux-musl-libgfortran5.tar.gz"
[[PROPACK]]
arch = "powerpc64le"
git-tree-sha1 = "ea8ab868d38163da65708bfe9c9dfb5628a2db99"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "e6eda32c99e6f0765620cb26902812bf9404369e5fe085bfff29a4e21f48b28d"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[PROPACK]]
arch = "armv7l"
git-tree-sha1 = "fe76178f54b1798248995158f36b0b494ac693f6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "b0eca1d5cadc60e4090599fb4f14a31b6451dbbf0363291de001a1a22b43c85f"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "25eb63d4e171b694d5152f2ce17d5b5429bd4ae0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "e6b11b2870c015c0f8715f6e32e08c9e8022935d7b7cddb0073797633e16f37b"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[PROPACK]]
arch = "powerpc64le"
git-tree-sha1 = "a6b04c423c2a2f55bfd28d56b484181ea1c55f7d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "963e91c9895b2e9b12226ef26e860556c14c7723ff06a81f5f807f219c9db1ed"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "0ec28629a818dee9a2352c7dee14e1dfb50e7922"
libgfortran_version = "4.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "451566eea1a1346799f889892b5a7c2a589026754642dae2f5ef0b070cbdb4e1"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[PROPACK]]
arch = "armv7l"
git-tree-sha1 = "0566bdc4f6f67683a7be72bb3b684a2f3bd66ca6"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "c4cb1275909f03e82238f55283431507ee131d9d8a4321ae6895c7eeba2068ca"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "b08f809b4b113f56621d26cdb3d3dd83008e288b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "d41557ac93df2a3d3e14e764b247c9242ad4f84de751dfaca6d7d6b727751458"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "ed95993f2c68adb50623a824898d90ac509c2b5e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "cf323811d2509b70d56862b3f7f542f5da05af628da7b812c35c8c648ceff4f0"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[PROPACK]]
arch = "armv7l"
git-tree-sha1 = "5bcde8d327463ce74476d689d9df722273e0e08e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "25d717f09522fe78d6a3fc7be31e90068004d1aef176f923508bf160b3404840"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "846ebba60fa6fa674994b09a4300dbf259a058c2"
libgfortran_version = "5.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "96564a7a3ab08573b276113f083c351698a2e0a239e58d5d85d6a0685c4e7f71"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "36b0c6b40fff96a4087fcf07fa5ba170ca025434"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "5a99ab04f6fc8621f149dc37096dfd725ce122d60d38182679ef38ba194ce13c"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.i686-linux-gnu-libgfortran4.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "8a11f45c4d61567086f935414d16de1f31344bf3"
libgfortran_version = "3.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "7d68868a6941bf69ca94c118e2ed19f2d3f4804d58523f8795403183c1b60fca"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "4359b7ae8d730a86e007077c14de6afb5060a576"
libgfortran_version = "4.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "b3701294766f8272486f581774ff9c1cfe1d9d1e23a05059204d6b28159ef96c"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "3bfce2536f2b8d7fd1c876fa3f0e3f2408ce7b3f"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[PROPACK.download]]
    sha256 = "b14e74a5ac3b55c59ce0989b3c01f1da98dd2259971af3c24228d0c8e3968066"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "6bd0c08ba9df6193e0b3543b14798f4210a5e134"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "7b933f622995e45ff9bfb315edd958fb59f8b819fcdcffefaa1560c501bf96ab"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "6f39b5e8e198d603363c5ea3a063f07dbac62687"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "77f0f2631150a702cf0cf51ed494b12b0f9f3f0572079ac32de36fcd23a31257"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "cf4c4425a4ffa1f518968a93d321c1e0c1711086"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "b83f74a8fc95fb72a69cc6221c5f358db7b9ea346e4719414c8faf411eda857e"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "711e24b7869ef663cbca52bfa08c1e4c28710fb0"
libgfortran_version = "3.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "27014d76e8ce75465cdedea7b165bb0a5d05705fe94bb06de0caec028d602ba7"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[PROPACK]]
arch = "armv7l"
git-tree-sha1 = "c8ebdffc0e218c9031e26dfcd745de48eb7f724e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "6960430eed2039ba18d5bd2c0d78644a3f3cc390cc71ddba612eefd8ff744938"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "bfd2a6c68e28a37e71d5847122fca27bf0d4aa48"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "2a40fe38be1ff4051095fd34b2913a5be36a980b0d523b1edce846f9c6401f29"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "3d8ecec48dd1c1aef5041f8dcf62692048787201"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "283a2fc75b439bdb47837a4b45df29eec9676ae6744781a23f30d3aab0df906b"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "66011490b939f225d8845e3ff5348e3569944d6f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "e7bc576ec5cd02647063e9f6c08ea82b0a996f28ab25d52a494285fdf487f1ae"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "d3c9e87f8f3e7dd6c8f459b11fa9f9aeaea9f0ad"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "f34b428e4cc470deae288ae5274f9e25578ff984fa1479708ebd42d3532e8998"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.i686-linux-gnu-libgfortran5.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "436c2fd520bcdbf89c82876e4cdd8452ed5b33e3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "8be3e982376c078862b5c0673994d2371cf14b7d4a881373e1cec19f6f88e561"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.i686-linux-gnu-libgfortran3.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "5a3645cbbc98c29ddbc7baef806264c6085453b6"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[PROPACK.download]]
    sha256 = "34dee86e614a30cfada69165f0060eb96aad792c2e0deea8d8954f27c6bb7831"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "7d2646fcbb12d6d7cf8cbbfe642dc3c8842b29b4"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "c7e0113e460802b714cf2aa01cdf6b6d902388397214c50100f7a48a7dea93be"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.i686-linux-musl-libgfortran3.tar.gz"
[[PROPACK]]
arch = "armv7l"
git-tree-sha1 = "f868b0046c120dd2c898af9e03d1eba43acf6619"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "3bacd62271542b20b1dff0f794533cb180894ed281a78dfaf27bf78f84f71247"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "15cf93e3f5e398ac179023524dbbd3a8dbbfea7d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "b757331e33118a5a824e68b4fd74f4e17e3c06cf924ba90e78acc51721d68614"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.i686-linux-musl-libgfortran4.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "3c1cb0b2eb44aec5194c7c1f8000ec98cf24f93b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "4fc7b846a0e70545ba3366847cbd146cfdb7f19ad1d39cff352ff44dfb6f6d92"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[PROPACK]]
arch = "powerpc64le"
git-tree-sha1 = "fc1ade0098dc648765740a2a61a9bf2ba643c9bc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "d1ceb53bf03c58f3d3775da13acfa7fd0c5ecceb1a06cc8311348cc843b210bd"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.1.0+1/PROPACK.v0.1.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
