[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "3640815101b0ef824e2d36381aa0800bd5e29af0"
libgfortran_version = "5.0.0"
os = "macos"

    [[PROPACK.download]]
    sha256 = "ebc996190989484b5603c1af20ae3dc7112322495c2f1b1bd0768f3fc567412c"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "71c4f8ed7912e524330f8974e41a75b34402f3e2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "812f40c2a53c508620c245e60c8a70878e3eceeb5eeb447fa453a8500ee46875"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "81095993d1f69c202c5fc496ac0c050f6c8f4e76"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "a53293b7bce3b4379cca4853f6dda882e09482bc99db699a5089cae4ad9eb134"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "5eab2310b811e5473441c2510c2e307aa530062b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "6bd881aa08db0b02576dfb7af407af36a7eae9da467c31df5672880e71f25dbc"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "9594fa3e9fd57f7354bceb9955ac05c81ef9c979"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "878ef9ee942303af4c6031d9981be6c9e95db106d26d69db7e84f161f13f48c9"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "e3c89a9c7b766915d8ed098f35203d5701d34cb4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "0f658508ed6a45a1b9d8b97da1cbbcc0c92287a2fe9638d70a0fa26444c883f4"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "3791b0b1df382157da0ce02d4f33df2172101e84"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "13ec631477b9e1b0c46f3bc04bb862082a0dd9557fe9f8f24066ada46848c505"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[PROPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8ecfb4b5b09c14496a0306b4ebac40221690cd8f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "c1acf603293a773dbf9b34443a9063bb184cce9fbe1c27141f51f15d9eeecb63"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[PROPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5272bd6bcc93b075904b5dc7ddd41155cedbeeec"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "09ef4b7223e11b44310d42c265fefed6409510d88d2c183549f1668612bd090b"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[PROPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "435d7eeb9d1fb934d9edf9b77feff70112cacf7e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "82e5b2c9824e2e642ea55f19a15ea2c1c5f0ce0497e11e3d90952ac35620bbcb"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[PROPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "54aa477d696456282fa0a99e3cca9e0e4d9dd850"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "6b4a0bccc3d2d5f05ca20e9ef049c3eeb229d7997016e8290fcd84a9a51eabe5"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[PROPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6fc8b376fb56027914a7d0f61e546f585cf52b57"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "f8c0fa1efee048c3a2733f581d4e06a0fe2b5746bf893692fe0f197b5976e3b1"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[PROPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c7b9348cdef750584a1c7368dc7174a95b007521"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "2f9b4dd8daa0a48fbb08fd938d7cbac91a7b25bcce8868cb911ce3fb02f48b25"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[PROPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0705f48ed021d602d02883a523331f157ab8ffff"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "10981a8d7c16a66d2c248686e5f094521b1544dcfda47f0c589f303de2558eb5"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[PROPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d9b8a1c5ab5aba533500f4c89c4a0d540ddeaf06"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "c693b0aae26f1333f2cd9ca51420cd262addab7605f3144a3b07dbe2404898bc"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[PROPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b99fae44e14a367297ac39f3679275cb9c6385de"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "ce5a06fa326a8a42d4b1fa03cdac1be6b7fe73d4599b62e01016cd897afa425d"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[PROPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "077d58785e9e5a6cdde00133d880f3b744a8f8dc"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "f8225f56484ae2ee4c0d720c15ee4be54f2c44c43f64328c83bbf352ffcd52cd"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[PROPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e31f208c98ee778d2fb4f5da214550b1a0030129"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "716fcca0cd919dbd94e3cd6ae307a5837e47bd9bf3df7c10fe8c3ae5deafa717"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[PROPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b4d099855ccdcb0a24ac429a81dbe9835ca09e53"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "41aa1df87f738f1222030deef50bf6400d69ac34060b856e7e09595c8ae17708"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "db80843e5f47d67177b4d01a4a3b762269930d0d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "444e16a0d9eb6f7ad2d390f10c7fd29e36b7146b18d6b4ed967df4506cad25e6"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.i686-linux-gnu-libgfortran3.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "69b0880f6188ab08e9a1b972c95b0c36f0db8345"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "7999e4c58d8bc1d0dd1c7ea19e12d56c0209abcd57d30f7370e3459e37510da7"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.i686-linux-gnu-libgfortran4.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "413fb9045261d5d899b846bc1cf269eac0108a1a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "93a77f6d3bc89fae9998f16040e5d877aec8a4c36bc8c2f099f2a1e7daf14839"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.i686-linux-gnu-libgfortran5.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "572b47dfb99be860be6588c5197fafc9e788da3f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "8c7681bb8c32c41a2a0e0eba985365c9a43c1e053edd785aefc9920d1bff0509"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.i686-linux-musl-libgfortran3.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "cfc282704f151a596e9ca1ebbfe7e8d470a29fc2"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "8301ec4ab16565e30214f4108311f6ad055b39808e56fa6adaec5d543b141cf6"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.i686-linux-musl-libgfortran4.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "2378089636fb44f7883c7a5bc80f822b80b90161"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "0777aaa7d1acfe5e4dcd068773b6f7eaecef93b8c4b8c9923a3bcaa0b3d3bc22"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.i686-linux-musl-libgfortran5.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "f252720dbff87857528750af443175a1a53b41f2"
libgfortran_version = "3.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "f7f7429d4af68b54d92b106527d0ba9dc2e21190b25cc071ea50ee55e086d9cf"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "f57cc32dd5feb7635d29ebba2d1343fc69696269"
libgfortran_version = "4.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "d43aa8bd86aa931ac9364a44c6d2dfc3218828eb0ce119c3113e0674fed96f49"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "520db84cfd630a7133fb38556264eba093e31cd8"
libgfortran_version = "5.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "9c90734f1542934193a0924b9016b8b7d095cfd943ccd4c96a8cd59ec26bbc78"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[PROPACK]]
arch = "powerpc64le"
git-tree-sha1 = "1a7c2a495cca1cfc97ed1fc0e59d8119c9220a84"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "791551293cbf51f5c2ce06b85f7f43323726a38595a0dd1f4c019d592ebb7d22"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[PROPACK]]
arch = "powerpc64le"
git-tree-sha1 = "0140af1ed99900e708e0a711bc92a0e073c1a0dd"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "59d5db571f583c6c7cdccadee44d96a82f78bcba5773ff3f3a91c97bf20cd1e0"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[PROPACK]]
arch = "powerpc64le"
git-tree-sha1 = "ff82e0f7b0d7a545a40ab6d94695e66e1128d75b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "c5fe86a0fa5f0862d98b33661ec28b3fbf3cb59fbe0e5a1fd6a22e5e19124290"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "7b630e5f38a7bbbfd909b59f7ede01663059443a"
libgfortran_version = "3.0.0"
os = "macos"

    [[PROPACK.download]]
    sha256 = "c43329b7110d7e2ae8527f014a41cc9bb51eebbc7af2d4ab087a8f3e6130602a"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "fa69d2adf9f87ee82c6077c8d8ddf4d4817f7700"
libgfortran_version = "4.0.0"
os = "macos"

    [[PROPACK.download]]
    sha256 = "6ad63d9c6f7deb69fcd16a840cd96c2009442bdbe39a6ed509a289353f486ef7"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "067c201047107405e4005c56db02645571a08943"
libgfortran_version = "5.0.0"
os = "macos"

    [[PROPACK.download]]
    sha256 = "80cbebe7d1cfdb905c387161b714cbb295a349a6d29663c91e39e3cb4167040b"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "7fcb54fbd9e6a345cbd9c65b7fdc0ef636422e89"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "d2604c0ca082a75c4e46f7c40e1e4a96ec3fdddd9767430ea5182af9517cb01b"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "39b665e7d3e0db0af16324a2915e9dfa30d8f9a1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "5721dee910f8417fcf7215304091d6d90a4278b738d6d0f07a54deebf126fad2"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "7ac77abd1fa2e495eb04516a788332216bd7a270"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "bf08bfe2632d9a882ed10bccf7b4d6f2db5be31893782498c1c07b32fc15df43"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "3f347c0667d21608bda897e00c4790ff9994f1e4"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "5bdc7010ed4d81d32e41961c74093e5047d44f46642d625e28706fedbcfb5528"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "74f56c5aa9c1853163ed50fec1a0c8dfb0eccb66"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "e5ee55f712013f05be6c98e135d1db58003b5b0b81f6e2c929461a5dc6c4b182"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "7edf8d290dc1f163d091e0bf43c1c69e53030502"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "2ef3a7ffc4a01c581751287174c6b8b3c65017a75fd7fcf1522d012234723f6e"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "5c95c1cc57e84162335ba45fbea704cb5b5ecf55"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[PROPACK.download]]
    sha256 = "caa081d7b30197de76b250f304ef103fca7aa0565be20257c658796c67f16080"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "38340db1f32794b26c69f2bd583a8a702a78725b"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[PROPACK.download]]
    sha256 = "283d240acb406ea6d522dc36a7fbf2f677eabb814a8e67b67a01c3b312dcf606"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "2c22b833c45bc07da6e0d276b4972b4de201ad2d"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[PROPACK.download]]
    sha256 = "19561db730c377f83293615d3f392a4b7584aa70eee40e6922c004d8eeabaa1e"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "522de27c7c0d173807a32bd95aeccec5e63922e2"
libgfortran_version = "3.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "4c3d00249e43792269cb00cc29c471236690852a413ccbd2e5dc4ec37ccfe13f"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "36d53ac1dd82a24a9222e381a7e3a1dc6ef3f817"
libgfortran_version = "4.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "5a56840ba50486df70e5029328558515951273bdac941428b37a28944d15d36a"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "2fe102493bba866c72535925986313f46904779e"
libgfortran_version = "5.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "b7e15317f4a87a63d048a70716e512a729bb9a288b8a5a6581ab3866f7bd98ee"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.1+0/PROPACK.v0.2.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
