[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "3d36761b1e40a71e2d42b13066c1ee324f8a0aa3"
libgfortran_version = "5.0.0"
os = "macos"

    [[PROPACK.download]]
    sha256 = "b635af853f23902622714376e5d54c0c0daf30460aaaf87d580ad82a376eabb1"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "fb8361685c5ce5721f142dfe6a382220da7885db"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "d3d77d8659458774cd9b26bd5d02433312167294c97b44e16ba844459e2c3117"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "8451bd6fe52da2267111b058eccb9b2496c8e018"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "a94e4eb7a6844ad9b97c5356a4258022a41fd7490f738492143927ef11bed60c"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "fb63bca6c38f65492786bc337d5a42b32e43cd20"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "17e0a09ff563a4855cc139b412465c9151d65af7c164f75f93caa0c9dcfed3ac"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "e98b6b0040ed3af7b886f45ef102b9b66f14f581"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "7a0f9ba5aa927a122d0fbb0a753d50ba2232fb4bcc10e5ab30762b2f18195bfc"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "daa5e8f04487fe22f88f2eceef01692a4f65783b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "9220312a871f55ccd179260cbf2b181cb4cc33fc0484831496e18dd153e439b2"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "71cb71c388ce02ecea2e450b503644ac2715f792"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "ea45f72bb35b68c2a5b2a4a8f0198920b337316671d9652f0571532b9c586fc3"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[PROPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d992627e63070e4b5bae0779afaa2b4967a54449"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "391a2748340ec883c9cd3cf226efcd73b5e6c6acaf6b14ea3329937d770206af"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[PROPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "25c4c7c4877f47c0c23f94cd5874b7f2057c58f7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "607df84fa1471a88468d926c73bcb59afbaa0a53bbbeafc0f9a46878abe48394"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[PROPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "235d243911fc2af870e5c7b1703f2e17a9e6dfd4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "02bf55f26e3cb437360091481698a5d61801157f4baa7acf9b7f97caf02741f9"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[PROPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c5b875db3de7ef38a4dc4b836e38de9ec929aa09"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "200a9400aacba9b68adb46b23b8028e5e5dd2be84578e1d14131f95347334f03"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[PROPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "21c27adb2619f5f2d48c20371cdfa2e91b305e68"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "472e507b0fcdade0b132c76ede74dfcf81bb40c700cd6d0c48140154d5d057a0"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[PROPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d13740db963dd221f56cfc8f0359d8364d7cf3d3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "f24cc1d1d40b499c00db18f0b6140560b36dcf52f03ead2ec7a360c4f01aa965"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[PROPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "00e2fc9781ae0fe05f19b3d553612a9e61fa1141"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "3bacea9fc0488eb935cdf1f31f4e44a59338cef2a432fba90503dc4b6aabadad"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[PROPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "26ad237dff7495e8ac984589c3cab2c749b8fa9b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "5bbcfff976acc18b3daf4f95e9b78d70c6b306384a37ea1b09281276de669098"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[PROPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c2df548344146a74ce02dcbea7e6ddfce8e4d232"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "39f4ec99d29b97172f7999b6a76059a9326bb9360fe03aabe9cbafd28ea3c8a6"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[PROPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "31ab61068d15472177f37234368a1e2390379846"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "b43ae5719b14cac50cf959b8a1a3832d4e80fe878c04e9781936f2acdabb06de"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[PROPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b059bc6a381d1fd8e9ce7a5779d225646bee3a35"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "ce2c09dcebfb98836ec1eec2c85a1f72b598fbffacfecf39500a59e3722663ea"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[PROPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aeb2dd2a6aa130b6789110202e00286ec7a29bf1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "623654f4b1e536da6000370e17e820c2459da3e7b2e35f92d354625598eced0b"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "915c5f1a3c1b87cc7f511b5d1f776067751d763b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "7bde5b5575d9ea5acb8e3d694e2b9b85d2aac9c2b9df003a436ba7e4c0b1ffa1"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.i686-linux-gnu-libgfortran3.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "88013cc0b024972cfbc435723b99384836c2ebf7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "81e4c89620e498910bc221721b66bd1e32c2ec87cc850e2f815b54a4eb8da79c"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.i686-linux-gnu-libgfortran4.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "3e76aa2a2b7bdb2fe9d144c13a07ef9db82f1937"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "bdf6f6c4c513a21d1797435d1fa808560a03f3309d886167de8e5f7aeb201456"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.i686-linux-gnu-libgfortran5.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "8b8d374073db8db8c75856e71b56c96e14747c06"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "c90e8d5e6d6e01b4904241bb11b7a1f2903772aca3273d5d36493eba15003a04"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.i686-linux-musl-libgfortran3.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "0de32597531e8f3de843b00bf8888b0a148aa864"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "2606ba6b1fb12d86a72f7637202fa59ef762d33095d333b291af508f68c149b0"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.i686-linux-musl-libgfortran4.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "209b017eaf34855fe17aed4f75b91cca619891d9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "fbd899ecefa6a517508b09d8dea53153ca11744f6fa0eb8b0f38c4a35c528b56"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.i686-linux-musl-libgfortran5.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "eba84a1a37e54725c255d5e3c84147377c57818b"
libgfortran_version = "3.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "320f605dd60fe9279561c93a5850379c889daecf2caac4ef6857784d4abf72a7"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "9be78f4cf55e7d568cebeccc44cf0c523c4c9bc9"
libgfortran_version = "4.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "96d061ae9cfeac53e91f65b225d8207aeeb1dc86e93aa19f4c84b812e53c3765"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "0a9b645dbcb6b55b6abc82185eeec417efe610f7"
libgfortran_version = "5.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "10da3c9a1b1f6eaab431f74f58e7dea959e061f34a697a8d686a0a69ea66fb8b"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[PROPACK]]
arch = "powerpc64le"
git-tree-sha1 = "2f657e81bcc54e5db77bc96ede6f8b5032db91da"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "f96c374f0864c912c8ece54977cdc3b23fe53d45c580ccf3275cebfaa965482d"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[PROPACK]]
arch = "powerpc64le"
git-tree-sha1 = "4c0ab6b2e06acdcff46df511a6a09302a5959037"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "beb000a182ba2ddbb930e02d36f8c81ca7a978afae5a0c8832495832ee0a3004"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[PROPACK]]
arch = "powerpc64le"
git-tree-sha1 = "d2621fd68e8b507360d2d9a27f703fc8291f519c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "5a837d099b1b36d1782fd5d4a61308e0cc35663fec1f394c2365887bed137b73"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "fa2df26e92460ff3514a53bfbb17a5522d63f6d6"
libgfortran_version = "3.0.0"
os = "macos"

    [[PROPACK.download]]
    sha256 = "bd10e462b696ce12be03d89571f7c01b755e9bec27ef272d4b2ee6b68377fc7e"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "151a68d90b84e1d9e67d5dfdec9cccc874bde0e8"
libgfortran_version = "4.0.0"
os = "macos"

    [[PROPACK.download]]
    sha256 = "e996c1d7e2b2e71488fe3692c4988b73b468c7621e7b021f0f1342957812975a"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "7687445a07501125a6ab43249192d27bd2609c6d"
libgfortran_version = "5.0.0"
os = "macos"

    [[PROPACK.download]]
    sha256 = "165207f483c1c0de5a82812d9e8f12bfea9967c0018604b972ad14bfe18e29b4"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "e1fb2a2d2fbe9191785cbeae0d3aec08450bb44e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "2fc304333424a083da5ba703afb9b2d914e58ad23aa48c78a3afe53505c96fd7"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "c8abe7e535e5cc6a099607d9892be84ddf02979c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "a2bd3fa9c544d7c627b0f2dc6f472411355c5d4a3ce957364808d45236d78048"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "b72560f865c96feb50e89572ef6b21fe62a9862c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "b9600c70292a7759244e8283275b6818e0389c7af352f1965b835d9372c477d0"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "1fb2d42aa3245a53eea85d70217b166eab02bdf3"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "388b30c68197c81104be6fd9acf999902ee057e13e55f50f6f7d66c2fd6b0ce8"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "d429700fca687e130f33555da25a775cecbf1108"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "3724ebed9bb1d1f0a70aad4e3986e0e61788b8b1798e2923ef4d77c6a61bf4fd"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "ee4d522375ff5d6984128e97b4e1189be1559bfa"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "063de03781c1612bf717ad5eb27373c4507ec900695b93d9d7ad58dfa8b0c53f"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "06ba5ede44820e9468f803ceebf0bc1d90b14369"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[PROPACK.download]]
    sha256 = "e98e122ee450d340228d1b518b9673304395b58e2bb8577bd4d5b40fb7c1d7dc"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "35fca6c2c3f2e127e9444420cc33605696a31582"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[PROPACK.download]]
    sha256 = "99759a721f319e6afb399f77c448c29a844adfc64db644fcd4ad4987831efd16"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "4bf5019e64955080b3c6d0682a4a0ce14c1837f3"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[PROPACK.download]]
    sha256 = "a1c2f76167e9e2994c90cb70affc0c61e7e861e3449e8c337d0422fa2f92bdb6"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "7125679ee7decae68e933f0696ce9cd96523578e"
libgfortran_version = "3.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "e530291ee1e82e99b2da80da8087c6e2f720eb1c82e3d83676488aaaf70fe20e"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "3b8efeb0546e7326faa0219f2928f9c41fa0a663"
libgfortran_version = "4.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "b688c5e361700c3125f7ec2008368462871710f6f37b36ba7cd22d1ef337a584"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "116738105924346ca1c5752ffe0070268467a7e5"
libgfortran_version = "5.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "83440ac03aae6201a146adaaf44c6ae6db741fa45ed55324ee278336a90c9163"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.0+0/PROPACK.v0.2.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
