[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "7e9f25bc73c062a3361daae498b474deac1255f6"
libgfortran_version = "5.0.0"
os = "macos"

    [[PROPACK.download]]
    sha256 = "fffb8a40386bacc73268d8ec6208208ab6fe9f4bbebb00197d29d061017f48d3"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "7e6247bf782063f286e2cecd0f8b668bc64d124e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "aabdcfbf36a914c3ca6db62e591bdb81d911bfc455e9ee63c76d76aeb8769f40"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.aarch64-linux-gnu-libgfortran3.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "ce24ffed0ba9eebd849ea50fcad50860054a533e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "e7ae6fe74fce534c425bcc26a891450ae84090eb23d240c32c1aeb030111826c"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "70f4bfe05979fc1e903cfe985be8af99f3072905"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "0ebb318b34f06ba427b685f5498721afc148f33d29765acd180510ab02777aec"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "3413ce91360b0b23871da7350f38e83fb17579bf"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "f779d89d75e73dd60e1f2296813b2d1534e3193325768f08016908f003599d55"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.aarch64-linux-musl-libgfortran3.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "10e1060b2cc86b80aa30d4f8db2ee3275324b48b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "ff92590a31c3bb664e62e4652d15f2a579a6d33b35a472b2647a605b63a0a05b"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.aarch64-linux-musl-libgfortran4.tar.gz"
[[PROPACK]]
arch = "aarch64"
git-tree-sha1 = "3b5b90f96fb288c3b4a6947c2ad1cc0b5744d157"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "6df3840b41fd7dd2ca3a622440c381de2e8162238c257024a9b2188b418bbdd8"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[PROPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b5f3c7c7e6d96bb9abe6301768a9cc3f809d6160"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "ba7329a8475b7a21a71c62ed2e11103f4dd20ad3f4771e05880d5d7e6c5de4e9"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[PROPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3ff8b301ad3579377037b98b2a1928231000a5dd"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "abc2c67baee64e232a42d75be4774d2d4d51510f6d8eaa15d2deae8776de0eb1"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[PROPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f8805bec239e1be247dd605ae9be37feb3f69d5c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "8feab7f8db2e2ae4c9d05e9661b1e3a174f684dee3c722fc4bc24b48167d5d4d"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[PROPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d37fd73da13ad3940c4bff9177efab3bc0e90d9d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "179323b6ee34f651907d278a040d55de92f01c7f0d36b9c3eca999c537caadb6"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[PROPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "43913dd93ae50c006381989a8054c7f22d77b61f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "c39e61323fe7e2e7a6166740053061e3b6c130fbed10e4368972cc5239d88afa"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[PROPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3489c72738080c6f9dbc80ad61416cd5d6c094b6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "05540039f94fe504f2af1f15229ff90c796bd6061c24079e24b97e93539a5d06"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[PROPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ad16205ba26f8e726088cc0d57c1492b63e09a3d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "71118d80f8724d3c0fd80e5840e658d2ef3b4e800136f3e6890b54efae687809"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[PROPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cc572808b76cbfd705eab270ffef37a4e66c9e79"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "c4694a8f5783269cfd0985f7f0176a0bde92a73b4b1cd97327767a4e0ea5cd74"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[PROPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "689167a10a2d8a334430d064f01469ffb5d3841b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "0bd8d7f201f4fda832da1ffe2ad8bfc68a72a723b8a783b41b626821f3f76e2f"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[PROPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7eaeffddc4feccfb0b728c256136049d60278264"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "e52265eca647c8569d72a3ada79c8d4b427b8d753382e35257808123a8d37c88"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[PROPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "14a64698082cc38d905d3f6adcb57fbc5bdfcede"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "11d520978d9b8db6ac2b9a070d2bac35e0b5eae0b5a3839a9e6bbe5f63249b38"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[PROPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0e98c06020619f0d1572434abfa0eb3cf2d74dc5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "f00cfebdb0c9a5a1d5a5dab14fd9bfe2dc56c016e0c00f409ed96f5793b3eed2"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "6468bdf804e223d8f95dfab3f37b2f7f69abfcab"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "159a04cbf84a70ce7945733ade0a86e2a1b2b0dddd3e5f5f9a172d3cf85a7651"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.i686-linux-gnu-libgfortran3.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "7786c6ea6daf99c875cfca61f7f560da1af1d0a8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "0bb12549b855d57fc7439b3f25886829f0c4d846c3191b0955b53602d44dfcba"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.i686-linux-gnu-libgfortran4.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "e8df1adf2509f7dafa5e729b0bb8940f8f8677d8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "bb558ce71866951e9b6416aebc5202b8b989decf7029f7e10ab74e77829bfe16"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.i686-linux-gnu-libgfortran5.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "b59cfd19e1789a8ca3323bb783fdd8760d50964a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "d4ebff75fca098eb6e5ca6dbc163d06eeab041a0e0d67d8c4134982a35fc0755"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.i686-linux-musl-libgfortran3.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "a272c3a928ad4cba1f465754cf13f6c81faa61e7"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "c6f38882ebcc3512eef9131b773191fd4c5f75f4f3d1b0e328f6adfdb8edf744"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.i686-linux-musl-libgfortran4.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "a6bf8f8934b292526421aef4e210d6a9d4822d7f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "5443b2d8cf7985934bba6e29e8f0104583d171a3318958c4169f503d16968f09"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.i686-linux-musl-libgfortran5.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "8c53669adf763221afff8e098b9877ef7cdd7a98"
libgfortran_version = "3.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "a914304311cdae821890012307c8e128e4b427ddbe0167781d55f80388df3b8e"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.i686-w64-mingw32-libgfortran3.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "94d0270303e28d590176a55973850abb885d163d"
libgfortran_version = "4.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "97d3838bff3dc7f05b5e2df052ba733dbe15ee7f3dae4c1b7fce608886940bcd"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.i686-w64-mingw32-libgfortran4.tar.gz"
[[PROPACK]]
arch = "i686"
git-tree-sha1 = "1f3d2ee275ad3a4a2b0a6ee53d9089ef752d22b3"
libgfortran_version = "5.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "81335d71063b812ec91bcd200eebac7e09e517f77f889d3470d49f6ffed623af"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.i686-w64-mingw32-libgfortran5.tar.gz"
[[PROPACK]]
arch = "powerpc64le"
git-tree-sha1 = "6e0fd2857c4e18e5dfdc45d0735364d8e00c40d4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "f13037e3ac2922f78345beaaf3b622955c3e4a89e20ee6af1885cbf12b769d2f"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[PROPACK]]
arch = "powerpc64le"
git-tree-sha1 = "1a42b6c8f1e0bcb93248d72f7c11f68159e3c0e5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "2de508b4e6f48471a4803bdbf07ca9ba42caa978fb5f3b74e55324bf09c7cf75"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[PROPACK]]
arch = "powerpc64le"
git-tree-sha1 = "638c1f95220a307e867170a8b2f15f682e0d41ec"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "32c6df9535990ef0195ad28bb19d61e6b999c24637c4f5cc300bdd29f010da0f"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "6f102fc2850b36ded304d5bccbe866cfb5303e27"
libgfortran_version = "3.0.0"
os = "macos"

    [[PROPACK.download]]
    sha256 = "08e433aebaf3a1b28a9f785b5439cc243e8b48a763f97129f18ee028a10128d6"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.x86_64-apple-darwin-libgfortran3.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "8c2df1a66075e0153bd85ccec3b09797327449c2"
libgfortran_version = "4.0.0"
os = "macos"

    [[PROPACK.download]]
    sha256 = "ea06bc0278be57b20a2166f0f76a62207c0018cf231555011c44b6a0de0fcd41"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "b5450660273dcf20a0654fa6ac32db3fde0cedec"
libgfortran_version = "5.0.0"
os = "macos"

    [[PROPACK.download]]
    sha256 = "adfdd16fd398f7da7fcf09092dfe26661c602886af32ce643f0eeb7b7c00ba65"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "81dd1681c86a5cae2635426004ddf55e602925b4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "20a9fdf79872b3e055931642aa53ca9eb7b8a615c753c1e57e35a62623ef8144"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.x86_64-linux-gnu-libgfortran3.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "f04acaac9b9336271418919d3deadc5f3590afac"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "0da48c8802d99b44e9f6868c63cedf19f704ac888d0077042649a6bf32f52405"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "98d9b9392d77186532f98ced581a8597d66885a2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "23faa15273d246f3bb022686e8de6cfbf51ac62ab710b67da87980594df4e1f6"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "372d2278f0c4d5ef9155a60d66de1494418437bd"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "7676963d68b28cbddb8717e5efbdac5f35ae4c35b1d94be1e4511a5c7267683c"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.x86_64-linux-musl-libgfortran3.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "9179ff9e028ec20577b0c946da1390373c80366b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "67e98dd402999e0c968a49a56465d8ecd93733e3998f16a60450019c113f1827"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "77217a174dabb2c5682a4e6be819218eaa776f7f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PROPACK.download]]
    sha256 = "0651834e0e1020d712e3603488ac4c2a5bd7d0acbac015dfafc6279609e964c5"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "d9d672c0104d9b2b988161d641dec28cb68572fe"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[PROPACK.download]]
    sha256 = "2ac8b33cdb65b903cd9798eb3870b63c6d249f3d6bf3234395fd8a2e85189f36"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "e3805584dd3e852a293f9741d5170ab723785e6a"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[PROPACK.download]]
    sha256 = "809734e8ba810edd7ec7746f26393f34f803c3a1401f8e56f76f3e4eb2bd93eb"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "4a36eea26087cb0149b7d2f51a73504db67f07ff"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[PROPACK.download]]
    sha256 = "191331a3d59fbb3cdda09acc1ce77eb8ed43a026ab4564a3d10b02dac454ca53"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "2f9f061d86108fd8edf35ea594b35ec75080329f"
libgfortran_version = "3.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "e1aed62521dacfac8cf4a42dba54e306460aa8460b9ec2eeafd27287d2677b28"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "1d396a212fda8393429ed0605831bfa1d1453bac"
libgfortran_version = "4.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "69ca0361874643e4d7482d8a97c3d4fff7aeff10e7f832518bc98fa803b19270"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[PROPACK]]
arch = "x86_64"
git-tree-sha1 = "a103daa18b57b34cc184bafb7d4aaa719065bc7c"
libgfortran_version = "5.0.0"
os = "windows"

    [[PROPACK.download]]
    sha256 = "203610f2da64b59e5f718ad9550a9886380e14767849621716a398b3223c12dc"
    url = "https://github.com/JuliaBinaryWrappers/PROPACK_jll.jl/releases/download/PROPACK-v0.2.2+0/PROPACK.v0.2.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
