# Autogenerated wrapper script for PROPACK_jll for x86_64-apple-darwin-libgfortran4
export libcpropack, libdpropack, libspropack, libzpropack

using CompilerSupportLibraries_jll
using libblastrampoline_jll
JLLWrappers.@generate_wrapper_header("PROPACK")
JLLWrappers.@declare_library_product(libcpropack, "@rpath/libcpropack.dylib")
JLLWrappers.@declare_library_product(libdpropack, "@rpath/libdpropack.dylib")
JLLWrappers.@declare_library_product(libspropack, "@rpath/libspropack.dylib")
JLLWrappers.@declare_library_product(libzpropack, "@rpath/libzpropack.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, libblastrampoline_jll)
    JLLWrappers.@init_library_product(
        libcpropack,
        "lib/libcpropack.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libdpropack,
        "lib/libdpropack.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libspropack,
        "lib/libspropack.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libzpropack,
        "lib/libzpropack.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
